---
title: "p8105_hw5_amv2187"
author: "Alyssa Vanderbeek"
date: "11/7/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

theme_set(theme_bw())
```

### Problem 1

```{r}
patient_data = tibble(
  patient = list.files('./data/problem1'), # get file names
  data = map(paste0('./data/problem1/', patient), read.csv) # read each file as list entry in column
)

head(patient_data)

patient_data_tidy = patient_data %>%
  unnest(.id = 'patient') %>% # unnest the list column of patient outcomes
  gather(key = week, value = outcome, contains("week")) %>% # wide to long
  mutate(arm = str_sub(patient, 1, 3), # get arm assignment from file name
         patient = as.numeric(str_sub(patient, 5, 6)), # get patient id from file name
         week = as.numeric(str_sub(week, 6))) %>% # make week indicator single numeric value
  select(arm, patient, week, outcome) # select and reorder desired columns

str(patient_data_tidy)

```

```{r}
patient_data_tidy %>%
  mutate(id = paste0(arm, patient)) %>% # create one grouping variable of arm assignment and patient id within that arm
  ggplot(aes(x = week, y = outcome, group = id, color = arm)) +
  geom_line() + # spaghetti plot grouped by patient
  geom_smooth(method = 'loess', aes(group = arm), se = F, lty = 3) + # fit smoothed curves for each trt group
  labs(
    title = 'Patient outcomes over time',
    x = 'Time (weeks)',
    y = 'Outcome'
  ) + 
  viridis::scale_color_viridis(
    name = 'Treatment group',
    discrete = T
  ) +
  theme(legend.position = 'bottom') # aesthetics
```



### Problem 2

```{r}
homicide_data = read_csv('./data/problem2/homicide-data.csv') # read in data

homicide_data_tidy = homicide_data %>%
  mutate(city_state = paste(city, state, sep = ', ')) %>% # create city_state variable
  mutate(unsolved = str_detect(disposition, 
                               paste(c('Closed without arrest', 'Open/No arrest'), 
                                     collapse = '|'))) # logical for unsolved yes/no
homicide_data_tidy %>%
  group_by(city_state) %>% 
  summarise(n_homicides = n(),
            n_unsolved = sum(unsolved)) %>%
  knitr::kable()
```

```{r}
homicide_data_tidy %>%
  filter(city_state == 'Baltimore, MD') %>% 
  summarise(n_unsolved = sum(unsolved),
            n_homicides = n()) %>% 
  mutate(tst = list(broom::tidy(prop.test(n_unsolved, n_homicides)))) %>%
  unnest(tst)

city_prop = homicide_data_tidy %>%
  group_by(city_state) %>% 
  summarise(n_homicides = n(),
            n_unsolved = sum(unsolved)) %>%
  mutate(tst = map2(.x = n_unsolved, .y = n_homicides, ~ broom::tidy(prop.test(.x, n = .y)))) %>%
  unnest(tst) %>%
  select(city_state, estimate, conf.low, conf.high)

city_prop %>% knitr::kable()
```

```{r, fig.height=8, fig.width=6}
city_prop %>%
  mutate(city_state = fct_reorder(city_state, estimate, desc = T)) %>%
  ggplot(aes(x = city_state, y = estimate, color)) +
  geom_bar(stat = 'identity', color = 'black', fill = 'grey') +
  geom_point() +
  geom_errorbar(aes(x = city_state, ymin = conf.low, ymax = conf.high), width = 0.5) +
  scale_y_continuous(limits = c(0, 1)) +
  labs(
    title = 'Proportion of homicides that remain unsolved',
    x = 'City',
    y = 'Proportion of homicides unsolved'
  ) +
  coord_flip() +
  viridis::scale_color_viridis(
    name = 'City',
    discrete = T
  ) +
  theme(legend.position = 'none')
```

